version: "3.8"

services:
  app:
    image: php:8.2-apache
    container_name: php_app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}

